import './styles/globals.css'
import './styles/hljs.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'StaFi Improvement Proposal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
